
auth.token=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

defaults.org=nn-inc
defaults.project=fable-talk-ai

defaults.url=https://sentry.io/
